config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  post 'upload', to: 'pages#upload', as: :upload
  get 'normativa', to: 'pages#normativa', as: :normativa
  get 'about', to: 'pages#about', as: :about
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner">
  <%= render 'shared/navbar' %>
  <div class="container px-3">
    <h2 class="color-title">Sistema de Análise Acadêmica 5.0</h2>
    <h5 class="color-title text-subtitle">Residência Estudantil: reduzindo distâncias, ampliando horizontes...</h5>

    <div class="text-center form-box">
      <%# <p class="text-light m-0 pb-2">Selecione o arquivo em PDF do histórico a ser analisado:</p> %>
      <%= form_tag(upload_path, multipart: true) do %>
        <div>
          <%= label_tag 'historico', 'Escolher Histórico para Análise', class: 'btn btn-branco-brilhante mb-2' %>
          <%= file_field_tag 'historico', accept: '.pdf', class: 'upload-input', required: true %>
        </div>
        <div class="preview text-light preview-display">
        </div>
        <div>
          <%= submit_tag "Analisar", class: 'btn btn-success btn-hidden btn-analisar mt-3' %>
        </div>
      <% end %>
    </div>
  <div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small">
  <div class="container footer-container d-sm-flex justify-content-between align-items-center">

    <!-- Copyright -->
    <div class="footer-copyright py-3">
      Copyright © 2022
    </div>
    <!-- Copyright -->

    <div class="powered">
      This system is powered by: <span class="d-inline-flex rosenaldo"><b><%= image_tag("rose.png", height: '20', width: '20', class: "rose") %>Rose <%= image_tag("coconut.png", height: '20', width: '20', class: "coconut") %>Naldo</b></span>
    </div>

  </div>
</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<% if current_page?(root_path) %>
  <nav class="navbar navbar-expand-sm navbar-dark">
    <div class="container py-0 container-navbar-banner">
<% else %>
  <nav class="navbar navbar-expand-sm navbar-light navbar-colored">
    <div class="container py-0">
<% end %>
    <%= link_to root_path, class:"navbar-brand nav-logo" do %>
      <i class="fas fa-university"></i>
      SAA 5.0
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <%# <li class="nav-item pr-2 active">
          <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
        </li> %>
        <li class="nav-item pr-2 <%= 'active' if current_page?(normativa_path) %>">
          <%= link_to normativa_path, class:"nav-link" do %>Normativas
            <%= (content_tag :span, "(current)", :class => "sr-only") if current_page?(normativa_path) %>
          <% end %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(about_path) %>">
          <%= link_to about_path, class:"nav-link" do %>Sobre
            <%= (content_tag :span, "(current)", :class => "sr-only") if current_page?(about_path) %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>

</nav>

app/views/shared/_slider.html.erb
<div class="mt-4 d-flex justify-content-center">
  <div id="carouselExampleIndicators aaa" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag("doors.jpg", class: "d-block w-100", alt: "First slide") %>
        <%# <img class="d-block" src="https://source.unsplash.com/ZFYg5jTvB4A/820x400" alt="First slide"> %>
        <div class="carousel-caption">
          <h3>1. Escolha</h3>
          <p>Faça o upload de um histórico acadêmico em PDF.</p>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag("doors2.jpg", class: "d-block w-100", alt: "Second slide") %>
        <%# <img class="d-block" src="https://source.unsplash.com/ZFYg5jTvB4A/820x400" alt="First slide"> %>
        <div class="carousel-caption">
          <h3>2. Analise</h3>
          <p>Realize sua análise apertando um botão.</p>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag("unsplash1.jpg", class: "d-block w-100", alt: "Third slide") %>
        <%# <img class="d-block" src="https://source.unsplash.com/ZFYg5jTvB4A/820x400" alt="First slide"> %>
        <div class="carousel-caption">
          <h3>3. Disponha</h3>
          <p>Aí estão os dados gerados.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/shared/_slider2.html.erb
<div class="mt-4">

  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item image1 active">
        <div class="carousel-caption">
          <h3>1. Hum...</h3>
          <p class="d-none d-md-block">Escolha um histórico acadêmico.</p>
        </div>
      </div>
      <div class="carousel-item image2">
        <div class="carousel-caption">
          <h3>2. Vupt!</h3>
          <p class="d-none d-md-block">Para analisar, aperte um botão.</p>
        </div>
      </div>
      <div class="carousel-item image3">
        <div class="carousel-caption">
          <h3>3. Zass!</h3>
          <p class="d-none d-md-block">Descubra os dados gerados.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

</div>